# Copy this file and Run from one level higher than the git pull directory
# To build: docker build -t opsh2oai/h2oai-nv -f Dockerfile-nvdocker .
# To run with docker run -it -p 12345:12345 opsh2oai/h2oai-nv

FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
MAINTAINER H2o.ai <ops@h2o.ai>

ENV DEBIAN_FRONTEND noninteractive
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH_MORE=/home/$USER/lib/:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LD_LIBRARY_PATH_MORE
ENV CUDADIR=/usr/local/cuda/include/
ENV OMP_NUM_THREADS=32
ENV MKL_NUM_THREADS=32
ENV VECLIB_MAXIMUM_THREADS=32
ENV PYENV_ROOT=$HOME/.pyenv
ENV PATH=$PYENV_ROOT/bin:$PATH

RUN \
  # Setup Repos
  apt-get update -y && \
  apt-get -y install curl apt-utils python-software-properties \
  software-properties-common iputils-ping wget cpio net-tools build-essential \
  git zip dirmngr && \
  apt-get -y --no-install-recommends  install \
      python3-dateutil \
      python3-magic && \
  wget http://launchpadlibrarian.net/326935544/s3cmd_2.0.0-1_all.deb && \
  dpkg -i s3cmd_2.0.0-1_all.deb && \
  add-apt-repository ppa:fkrull/deadsnakes  && \
  apt-get update -yqq && \
  curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
  # Install H2o dependencies
  apt-get -y --no-install-recommends  install \
    python3.6 \
    python3.6-dev \
    python3-pip && \
  update-alternatives --install /usr/bin/python python /usr/bin/python3.6 100 && \
  python -m pip install --upgrade pip && \
  apt-get clean && \
  rm -rf /var/cache/apt/* && \
  apt-get install -y libopenblas-dev

RUN \
    rm -rf h2oai_env && \
    mkdir -p h2oai_env && \
    mkdir -p .pylint.d && \
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    eval "$(pyenv init -)" && \
    pyenv install 3.6.1 && \
    pyenv global 3.6.1 && \
    pip install setuptools --no-cache-dir

COPY requirements_buildonly.txt requirements_buildonly.txt
COPY requirements_runtime.txt requirements_runtime.txt
RUN \
    . h2oai_env/bin/activate && \
    pip install -r requirements_buildonly.txt && \
    pip install -r requirements_runtime.txt && \
    chmod -R 777 h2oai_env && \
    chmod 777 /
