FROM FROM_SUBST 
 
MAINTAINER H2o.ai <ops@h2o.ai>

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH_MORE=/usr/lib/gcc/ppc64le-redhat-linux/4.8.2/:/home/$USER/lib/:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH:$LD_LIBRARY_PATH_MORE
ENV CUDADIR=/usr/local/cuda/include/
ENV OMP_NUM_THREADS=32
ENV MKL_NUM_THREADS=32
ENV HOME=/root
ENV VECLIB_MAXIMUM_THREADS=32
RUN \
    yum groupinstall -y "Development Tools"

RUN \
    yum install -y \
        which \
        ncurses-devel \
        zlib-devel \
        wget \
        bzip2 \
        openssl-devel \
        libcurl-devel \
        libpng-devel \
        freetype-devel \
        atlas-devel \
        blas-devel

RUN \
    mkdir -p /opt/h2oai/dai

RUN \
    wget -q https://s3.amazonaws.com/artifacts.h2o.ai/releases/ai/h2o/dai-python/build-python-4/ARCH_SUBST-centos7DEBUG_SUBST/python.tar && \
    tar xf python.tar && \
    mv python /opt/h2oai/dai && \
    rm -f python.tar

RUN \
    wget -q https://s3.amazonaws.com/artifacts.h2o.ai/releases/ai/h2o/dai-thirdparty-deps/1.0-master-29/ARCH_SUBST-centos7/llvm.tar.bz2 && \
    tar xf llvm.tar.bz2 && \
    cp -r llvm/* /opt/h2oai/dai/ && \
    rm -rf llvm*

RUN \
    wget -q https://s3.amazonaws.com/artifacts.h2o.ai/releases/ai/h2o/dai-thirdparty-deps/1.0-master-29/ARCH_SUBST-centos7/openblas.tar.bz2 && \
    tar xf openblas.tar.bz2 && \
    cp -a openblas/* /usr/local/ && \
    rm -rf openblas*
ENV OPENBLAS_PREFIX=open

ENV LLVM4=/opt/h2oai/dai
ENV PATH=/opt/h2oai/dai/python/bin:$PATH
ENV PATH=/usr/local/bin:$PATH
ENV PATH=$LLVM4/bin:$PATH
ENV LD_LIBRARY_PATH=$LLVM4/lib
ENV LD_LIBRARY_PATH=/opt/h2oai/dai/python/lib:$LD_LIBRARY_PATH
COPY scripts/gcc_wrapper.sh /opt/h2oai/gcc_wrapper/gcc
COPY scripts/g++_wrapper.sh /opt/h2oai/gcc_wrapper/g++
COPY scripts/gcc_wrapper.sh /opt/h2oai/gcc_wrapper/ARCH_SUBST-conda_cos6-linux-gnu-gcc
COPY scripts/g++_wrapper.sh /opt/h2oai/gcc_wrapper/ARCH_SUBST-conda_cos6-linux-gnu-c++
ENV PATH=/opt/h2oai/gcc_wrapper:$PATH
RUN ln /usr/bin/ar $LLVM4/bin/ARCH_SUBST-conda_cos6-linux-gnu-ar

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
WORKDIR $HOME

ENV PATH=/usr/local/bin:$PATH
RUN \
    wget -q https://cmake.org/files/v3.10/cmake-3.10.1.tar.gz && \
    tar xf cmake-3.10.1.tar.gz && \
    cd $HOME/cmake-3.10.1 && \
    ./configure && \
    make -j6 install && \
    cd $HOME && \
    rm -rf cmake-3*

# Install SWIG b/c yum has old versions
RUN \
    wget -q https://sourceforge.net/projects/swig/files/swig/swig-3.0.12/swig-3.0.12.tar.gz && \
    tar xf swig-3.0.12.tar.gz && \
    cd swig-3.0.12 && \
    ./configure --prefix=/usr && \
    make -j 4 && \
    make install && \
    cd $HOME && \
    rm -rf swig-3*

# Symlinks for CMake/SWIG - it does not recognize Miniconda paths otherwise
RUN \
    mkdir -p /usr/lib64/ && \
    ln -s /opt/h2oai/dai/python/lib/*python* /usr/lib64/ && \
    mkdir -p /usr/include/python3.6m && \
    ln -s /opt/h2oai/dai/python/include/python3.6m/* /usr/include/python3.6m

# Symlinks for NVML
RUN \
    mkdir -p /usr/lib64/nvidia/ && \
    ln -s /usr/local/cuda-MY_CUDA_VERSION_SUBST/targets/ARCH_SUBST-linux/lib/stubs/libnvidia-ml.so /usr/lib64/nvidia/libnvidia-ml.so

RUN pip install setuptools
RUN pip install scikit-build
RUN pip install numpy==1.14.3
RUN pip install llvmlite==0.20.0
RUN pip install scipy==1.1.0

COPY requirements_buildonly.txt requirements_buildonly.txt
RUN sed -i 's/cmake/# cmake/' requirements_buildonly.txt
RUN pip install -r requirements_buildonly.txt

COPY requirements_runtime.txt requirements_runtime.txt
RUN pip install -r requirements_runtime.txt

COPY requirements_runtime_demos.txt requirements_runtime_demos.txt
RUN pip install -r requirements_runtime_demos.txt

RUN chmod -R o+rwx /opt/h2oai/dai/python
RUN chmod -R o+rwx /root

WORKDIR $HOME

ENV GIT_AUTHOR_NAME="anonymous"
ENV GIT_AUTHOR_EMAIL="anonymous@h2o.ai"
ENV GIT_COMMITTER_NAME="anonymous"
ENV GIT_COMMITTER_EMAIL="anonymous@h2o.ai"
ENV EMAIL="anonymous@h2o.ai"
