FROM test/py
 
MAINTAINER H2o.ai <ops@h2o.ai>

ENV CUDA_HOME=/usr/local/cuda-8.0
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH_MORE=/usr/lib/gcc/ppc64le-redhat-linux/4.8.2/:/home/$USER/lib/:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH:$LD_LIBRARY_PATH_MORE
ENV CUDADIR=/usr/local/cuda/include/
ENV OMP_NUM_THREADS=32
ENV MKL_NUM_THREADS=32
ENV HOME=/root
ENV VECLIB_MAXIMUM_THREADS=32
ENV PYENV_ROOT=$HOME/.pyenv
ENV PATH=$PYENV_ROOT/bin:$PATH
RUN \
   pip3.6 install setuptools --no-cache-dir && \
   ln /usr/local/bin/easy_install-3.6 /usr/local/bin/easy_install && \
   ln /usr/local/bin/pip3.6 /usr/local/bin/pip 

COPY requirements_buildonly.txt requirements_buildonly.txt
COPY requirements_runtime.txt requirements_runtime.txt
COPY requirements_runtime_demos.txt requirements_runtime_demos.txt
RUN \
#    chmod a+rwx / && \
#    chmod -R a+rwx /root  && \
#    chmod ugo+s /root/ && \
#    mkdir -p /root/.cache/ && \
    pip3.6 install setuptools llvmlite==0.20.0 scikit-build scipy && \
    pip3.6 install -r requirements_buildonly.txt && \
    pip3.6 install -r requirements_runtime.txt && \
    pip3.6 install -r requirements_runtime_demos.txt

ENV GIT_COMMITER_NAME=h2o4gpu
ENV GIT_COMMITER_EMAIL=h2o4gpu@h2o.ai

RUN yum install -y which

RUN yum install -y sudo man gfortran-devel

RUN \
    pip3.6 install --upgrade pip
WORKDIR $HOME

RUN yum install -y swig && \
  ln /usr/lib64/libgfortran.so.3 /usr/lib64/libgfortran.so && \
  wget http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz && \
  tar xvf v0.2.20.tar.gz && \
  rm v0.2.20.tar.gz && \
  cd OpenBLAS-0.2.20 && make CBLAS_ONLY=1 && make PREFIX=/usr/local install

ENV OPENBLAS_PREFIX=open
RUN yum install -y libstdc++ libc libgomp
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
