FROM nvidia/cuda:8.0-cudnn5-devel-centos7

MAINTAINER H2o.ai <ops@h2o.ai>

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH_MORE=/home/$USER/lib/:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LD_LIBRARY_PATH_MORE
ENV CUDADIR=/usr/local/cuda/include/
ENV OMP_NUM_THREADS=32
ENV MKL_NUM_THREADS=32
ENV HOME=/root
ENV VECLIB_MAXIMUM_THREADS=32
ENV PYENV_ROOT=$HOME/.pyenv
ENV PATH=$PYENV_ROOT/bin:$PATH

RUN \
  yum install -y curl \
  yum install -y https://centos7.iuscommunity.org/ius-release.rpm \
  yum install -y python36u

RUN \
  yum install -y git

RUN \
  yum install -y make

RUN \
  yum install -y \
    openssl-devel \
    zlib-devel \
    bzip2-devel \
    readline-devel \
    libsqlite3x-devel \
    wget \
    curl \
    llvm \
    ncurses-devel \
    xz-devel \
    tk-devel

RUN \
    mkdir -p .pylint.d && \
    rm -rf ~/.pyenv && \
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    eval "$(/root/.pyenv/bin/pyenv init -)" && \
    /root/.pyenv/bin/pyenv install 3.6.1 && \
    /root/.pyenv/bin/pyenv global 3.6.1 && \
    pip install setuptools --no-cache-dir

COPY requirements_buildonly.txt requirements_buildonly.txt
COPY requirements_runtime.txt requirements_runtime.txt
COPY requirements_runtime_demos.txt requirements_runtime_demos.txt
RUN \
    chmod a+rwx / && \
    chmod -R a+rwx /root  && \
    chmod ugo+s /root/ && \
    mkdir -p /root/.cache/ && \
    eval "$(/root/.pyenv/bin/pyenv init -)" && \
    /root/.pyenv/bin/pyenv global 3.6.1 && \
    pip install setuptools && \
    pip install -r requirements_buildonly.txt && \
    pip install -r requirements_runtime.txt && \
    pip install -r requirements_runtime_demos.txt

ENV GIT_COMMITER_NAME=h2o4gpu
ENV GIT_COMMITER_EMAIL=h2o4gpu@h2o.ai

RUN yum install -y which
RUN yum erase -y git
RUN yum install -y git2u
RUN yum install -y ccache

RUN yum install -y sudo man

RUN \
    eval "$(/root/.pyenv/bin/pyenv init -)" && \
    /root/.pyenv/bin/pyenv global 3.6.1 && \
    pip install --upgrade pip && \
    pip install --upgrade setuptools

RUN yum install -y openblas-devel

RUN yum install -y centos-release-scl-rh && \
    yum install -y devtoolset-3

RUN yum install -y swig
