#' Random Forest Classifier
#' 
#' @export
h2o4gpu.random_forest_classifier <- function(
  n_estimators = 10L,
  criterion = "gini",
  max_depth = 3L,
  min_samples_split = 2L,
  min_samples_leaf = 1L,
  min_weight_fraction_leaf = 0.0,
  max_features = "auto",
  max_leaf_nodes = NULL,
  min_impurity_decrease = 0.0,
  min_impurity_split = NULL,
  bootstrap = TRUE,
  oob_score = FALSE,
  n_jobs = 1L,
  random_state = NULL,
  verbose = 0L,
  warm_start = FALSE,
  class_weight = NULL,
  subsample = 1.0,
  colsample_bytree = 1.0,
  num_parallel_tree = 1L,
  tree_method = "gpu_hist",
  n_gpus = -1L,
  predictor = "gpu_predictor",
  backend = "auto") {
  model <- h2o4gpu$RandomForestClassifier(
    n_estimators = as.integer(n_estimators),
    criterion = criterion,
    max_depth = as.integer(max_depth),
    min_samples_split = as.integer(min_samples_split),
    min_samples_leaf = as.integer(min_samples_leaf),
    min_weight_fraction_leaf = min_weight_fraction_leaf,
    max_features = max_features,
    max_leaf_nodes = max_leaf_nodes,
    min_impurity_decrease = min_impurity_decrease,
    min_impurity_split = min_impurity_split,
    bootstrap = bootstrap,
    oob_score = oob_score,
    n_jobs = as.integer(n_jobs),
    random_state = as_nullable_integer(random_state),
    verbose = as.integer(verbose),
    warm_start = warm_start,
    class_weight = class_weight,
    subsample = subsample,
    colsample_bytree = colsample_bytree,
    num_parallel_tree = as.integer(num_parallel_tree),
    tree_method = tree_method,
    n_gpus = as.integer(n_gpus),
    predictor = predictor,
    backend = backend
  )
  h2o4gpu_model(model, "xgboost")
}
