function pogs_setup(platform)
%% Setup script for pogs

% Change paths as necessary.
cuda_bin = '/usr/local/cuda/bin';
cuda_lib = '/usr/local/cuda/lib';

if nargin == 0 || ~strcmp(platform, 'gpu')
  try
    unix('make pogs.o -f Makefile -C .. IFLAGS="-D__MEX__ -stdlib=libstdc++"');
    mex -largeArrayDims -I.. ...
        LDFLAGS='\$LDFLAGS -framework Accelerate -stdlib=libstdc++' ...
        CXXFLAGS='\$CXXFLAGS -stdlib=libstdc++' ...
        ../pogs.o pogs_mex.cpp ...
        -output pogs &> /dev/null
  catch
    fprintf('Linking to standard library failed, trying another.\n')
    
    unix('make pogs.o -f Makefile -C .. IFLAGS=-D__MEX__');
    mex -largeArrayDims -I.. ...
        LDFLAGS='\$LDFLAGS -framework Accelerate' ...
        ../pogs.o pogs_mex.cpp ...
        -output pogs
  end
else
  unix(sprintf(['export PATH=$PATH:%s;' ...
                'export DYLD_LIBRARY_PATH=%s:$DYLD_LIBRARY_PATH;' ...
                'make pogs_cu.o -f Makefile -C .. IFLAGS=-D__MEX__;' ...
                'make pogs_cu_link.o -f Makefile -C .. IFLAGS=-D__MEX__'], ...
               cuda_bin, cuda_lib));
  try
    eval(sprintf(['mex -largeArrayDims -I.. -L%s -lcudart -lcublas -output pogs ' ...
                  'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' ' ...
                  'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++'' ' ...
                  'pogs_mex.cpp ../pogs_cu.o ../pogs_cu_link.o &> /dev/null'], ...
                 cuda_lib, cuda_lib))
  catch
    fprintf('Linking to standard library failed, trying another.\n')
    
    eval(sprintf(['mex -largeArrayDims -I.. -L%s -lcudart -lcublas -output pogs ' ...
                  'LDFLAGS=''\\$LDFLAGS -Wl,-rpath,%s'' ' ...
                  'pogs_mex.cpp ../pogs_cu.o ../pogs_cu_link.o'], ...
                 cuda_lib, cuda_lib))
  end
end

savepath

fprintf('Setup Successful.\n')

