function pogs_setup(platform)
%% Setup script for pogs

cuda_bin = '/usr/local/cuda/bin';
cuda_lib = '/usr/local/cuda/lib';

if nargin == 0 || ~strcmp(platform, 'gpu')
  unix('make pogs.o -f Makefile -C .. IFLAGS=-D__MEX__');
  mex -largeArrayDims -I.. LDFLAGS='\$LDFLAGS -framework Accelerate' ...
      ../pogs.o pogs_mex.cpp ...
      -o pogs
else
  unix(sprintf(['export PATH=$PATH:%s;' ...
                'export DYLD_LIBRARY_PATH=%s:$DYLD_LIBRARY_PATH;' ...
                'make pogs_cu.o -f Makefile -C .. IFLAGS=-D__MEX__;' ...
                'make pogs_cu_link.o -f Makefile -C .. IFLAGS=-D__MEX__'], ...
               cuda_bin, cuda_lib));

  eval(sprintf(['mex -largeArrayDims -I.. -L%s -lcudart -lcublas -o pogs ' ...
                'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' ' ...
                'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++'' ' ...
                'pogs_mex.cpp ../pogs_cu.o ../pogs_cu_link.o'], ...
               cuda_lib, cuda_lib))
end

savepath

