# Instruction:
# * Ensure you have the following R libraries installed via the following:
#   `devtools::install_github("rstudio/reticulate"); install.packages(c("stringr", "roxygen2))`
# * Change variable `pkg_location` below to point to your R package directory
# * Run `use_condaenv()` or `use_python()` from reticulate to activate the
#   environment with h2o4gpu installed. 
#   e.g. use_condaenv("r-h2o4gpu", conda = "~/miniconda3/envs/py36/bin/conda")
library(reticulate)
library(stringr)
library(roxygen2)
pkg_location <- "~/h2o4gpu/src/interface_r"

# Note: Code below should not be changed unless necessary
source(file.path(pkg_location, "scripts/gen_wrapper_utils.R"))
h2o4gpu <- import("h2o4gpu")
common_nullabl_int_params <- c("random_state")

sink(file.path(pkg_location, "R/auto_generated_wrappers.R"))

cat("# Note: This file is automatically generated by scripts/gen_wrappers.R. Please do not change. \n\n")

gen_wrapper("h2o4gpu$RandomForestClassifier",
            r_function = "h2o4gpu.random_forest_classifier",
            nullable_int_params = common_nullabl_int_params)

gen_wrapper("h2o4gpu$RandomForestRegressor",
            r_function = "h2o4gpu.random_forest_regressor",
            nullable_int_params = common_nullabl_int_params)

gen_wrapper("h2o4gpu$GradientBoostingClassifier",
            r_function = "h2o4gpu.gradient_boosting_classifier",
            nullable_int_params = common_nullabl_int_params)

gen_wrapper("h2o4gpu$GradientBoostingRegressor",
            r_function = "h2o4gpu.gradient_boosting_regressor",
            nullable_int_params = common_nullabl_int_params)

gen_wrapper("h2o4gpu$KMeans",
            r_function = "h2o4gpu.kmeans",
            nullable_int_params = common_nullabl_int_params)

sink()

# Regenerate NAMESPACE and .Rd files
roxygen2::roxygenise(pkg_location)
